const CookiePolicy = () => {
  return (
    <div className="bg-white min-h-screen">
      <div className="container mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold text-center mb-8">Cookie Policy</h1>
        <div className="max-w-3xl mx-auto bg-zinc-50 p-8 rounded-lg shadow-md">
          <p className="text-zinc-700 mb-4">
            This Cookie Policy explains how Juju, operated by Visual Core 9 Systems (operating as VisualHQ) ("we", "us", "our"), uses cookies and similar technologies on our website and services. This policy is compliant with the General Data Protection Regulation (GDPR).
          </p>

          <h2 className="text-2xl font-semibold mt-6 mb-3">1. What are Cookies?</h2>
          <p className="text-zinc-700 mb-4">
            Cookies are small text files that are placed on your device when you visit a website. They are widely used to make websites work more efficiently and provide information to the owners of the site.
          </p>

          <h2 className="text-2xl font-semibold mt-6 mb-3">2. Types of Cookies We Use</h2>
          <p className="text-zinc-700 mb-4">
            We use the following types of cookies:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li><strong>Essential Cookies:</strong> These are necessary for the website to function properly. They don't gather any information about you that could be used for marketing or remembering where you've been on the internet.</li>
            <li><strong>Analytical/Performance Cookies:</strong> These allow us to recognize and count the number of visitors and see how visitors move around our website when they are using it. This helps us improve the way our website works.</li>
            <li><strong>Functionality Cookies:</strong> These are used to recognize you when you return to our website. This enables us to personalize our content for you and remember your preferences.</li>
            <li><strong>Targeting Cookies:</strong> These record your visit to our website, the pages you have visited, and the links you have followed. We may use this information to make our website and the advertising displayed on it more relevant to your interests.</li>
          </ul>

          <h2 className="text-2xl font-semibold mt-6 mb-3">3. Specific Cookies We Use</h2>
          <p className="text-zinc-700 mb-4">
            Here are the specific cookies we use on Juju:
          </p>
          <table className="w-full text-left border-collapse mb-4">
            <thead>
              <tr>
                <th className="border p-2">Cookie Name</th>
                <th className="border p-2">Purpose</th>
                <th className="border p-2">Duration</th>
                <th className="border p-2">Type</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border p-2">juju_session</td>
                <td className="border p-2">Maintains your session state across page requests</td>
                <td className="border p-2">Session</td>
                <td className="border p-2">Essential</td>
              </tr>
              <tr>
                <td className="border p-2">juju_preferences</td>
                <td className="border p-2">Stores your preferences (e.g., preferred file formats)</td>
                <td className="border p-2">1 year</td>
                <td className="border p-2">Functionality</td>
              </tr>
              <tr>
                <td className="border p-2">juju_recent_conversions</td>
                <td className="border p-2">Remembers your recent file conversions for quick access</td>
                <td className="border p-2">30 days</td>
                <td className="border p-2">Functionality</td>
              </tr>
              <tr>
                <td className="border p-2">juju_analytics</td>
                <td className="border p-2">Collects anonymous usage data to improve our service</td>
                <td className="border p-2">1 year</td>
                <td className="border p-2">Analytical</td>
              </tr>
            </tbody>
          </table>

          <h2 className="text-2xl font-semibold mt-6 mb-3">4. Third-Party Services</h2>
          <p className="text-zinc-700 mb-4">
            We use the following third-party services that may place cookies on your device:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li>
              <strong>Google Analytics:</strong> We use Google Analytics to understand how visitors interact with our website. Google Analytics uses cookies to collect information and report website usage statistics without personally identifying individual visitors. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States.
            </li>
            <li>
              <strong>Google AdSense:</strong> As our service is supported by ads, we use Google AdSense to display relevant advertisements. AdSense uses cookies to improve advertising, such as showing relevant ads based on the websites you visit.
            </li>
            <li>
              <strong>Firebase Authentication:</strong> We use Firebase for user authentication. Firebase may use cookies to maintain session information and improve the sign-in experience.
            </li>
            <li>
              <strong>Anthropic Claude:</strong> We utilize Anthropic's Claude AI for certain features on our website. While Claude itself doesn't set cookies, our integration may use cookies to enhance your experience with AI-powered features.
            </li>
          </ul>
          <p className="text-zinc-700 mb-4">
            You can learn more about how these third-party services use cookies and how to opt-out by visiting their respective privacy policies:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li><a href="https://policies.google.com/privacy" className="text-indigo-600 hover:underline">Google Privacy Policy</a></li>
            <li><a href="https://firebase.google.com/support/privacy" className="text-indigo-600 hover:underline">Firebase Privacy Policy</a></li>
            <li><a href="https://www.anthropic.com/legal/privacy" className="text-indigo-600 hover:underline">Anthropic Privacy Policy</a></li>
          </ul>

          <h2 className="text-2xl font-semibold mt-6 mb-3">5. Your Consent</h2>
          <p className="text-zinc-700 mb-4">
            When you first visit our website, we will ask for your consent to use cookies, except for essential cookies which are required for the operation of our website. You can choose to accept or decline cookies. You can also change your cookie settings at any time by clicking on the "Cookie Settings" link in the footer of our website.
          </p>

          <h2 className="text-2xl font-semibold mt-6 mb-3">6. Managing Cookies</h2>
          <p className="text-zinc-700 mb-4">
            Most web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit www.aboutcookies.org or www.allaboutcookies.org.
          </p>

          <h2 className="text-2xl font-semibold mt-6 mb-3">7. Changes to This Cookie Policy</h2>
          <p className="text-zinc-700 mb-4">
            We may update our Cookie Policy from time to time. We will notify you of any changes by posting the new Cookie Policy on this page and updating the "Last updated" date.
          </p>

          <h2 className="text-2xl font-semibold mt-6 mb-3">8. Contact Us</h2>
          <p className="text-zinc-700 mb-4">
            If you have any questions about this Cookie Policy, please contact us at:
          </p>
          <p className="text-zinc-700">
            VisualHQ (operated by Visual Core 9 Systems)<br />
            5 Ado Ibrahim Street, 101212, Sabo, Yaba, Lagos, Nigeria<br />
            Email: art@visual.ng
          </p>

          <p className="text-zinc-700 mt-6">
            Last updated: July 19, 2024
          </p>
        </div>
      </div>
    </div>
  );
};

export default CookiePolicy;